### ISSUE TITLE
gridtext dependencies?

### ISSUE THREAD

**Issue by Nenuial** [clauswilke/gridtext#2]
I'm trying to install ggtext on a MacOS and when it get to the gridtext package I get a warning that says I need to install build tools. If I say "yes" it lead me to [this page](https://www.cnet.com/how-to/install-command-line-developer-tools-in-os-x/) but I already have the latest developper tools installed on my computer.

My question is: what could gridtext be missing? so that I can try to install it.

**Comment by clauswilke** [comment]
You need to be able to install R packages with C++ code from source. I don't know what the specific problem might be in your case.
